
CREATE TABLE `BOOKINGS` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `LAST_NAME` VARCHAR(50) NOT NULL,
    `FIRST_NAME` VARCHAR(50),
    `EVENT_SELECTION` VARCHAR(30) NOT NULL,
    `EMAIL` VARCHAR(50),
    `TEL` VARCHAR(50) NOT NULL,
    `PERSONS` INT NOT NULL,
    PRIMARY KEY (`ID`)
)